name: Container Builder

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag
        run: echo "JAVA_SPIFFE_HELPER_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Publish java-spiffe-helper
        uses: docker/build-push-action@v5
        with:
          file: java-spiffe-helper/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/spiffe/java-spiffe-helper:${{ env.JAVA_SPIFFE_HELPER_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            JAVA_SPIFFE_HELPER_VERSION=${{ env.JAVA_SPIFFE_HELPER_VERSION }}
